package com.jess.gdfp;

public class DatenObjekteKennlinie {
    private byte[] SECOND_KENNLINIE = new byte[200];
    private byte[] DATENOBJEKTE_KENNLINIE = new byte[200];

    public byte[] getSECOND_KENNLINIE() {


        SECOND_KENNLINIE[0] = DATENOBJEKTE_KENNLINIE[0]; //SYN
        SECOND_KENNLINIE[1] = DATENOBJEKTE_KENNLINIE[0]; //SOH
        SECOND_KENNLINIE[2] = DATENOBJEKTE_KENNLINIE[0]; //NA
        SECOND_KENNLINIE[3] = DATENOBJEKTE_KENNLINIE[0]; //Kom. stütz
        SECOND_KENNLINIE[4] = DATENOBJEKTE_KENNLINIE[0]; //msb length nutzdaten
        SECOND_KENNLINIE[5] = DATENOBJEKTE_KENNLINIE[0]; //lsb nutzdaten
        SECOND_KENNLINIE[6] = DATENOBJEKTE_KENNLINIE[0]; //crc8 length syn
        SECOND_KENNLINIE[7] = DATENOBJEKTE_KENNLINIE[0]; //stx
        SECOND_KENNLINIE[8] = DATENOBJEKTE_KENNLINIE[0]; //msb kennlinie nummer
        SECOND_KENNLINIE[9] = DATENOBJEKTE_KENNLINIE[0]; //lsb kennlinie nummer
        SECOND_KENNLINIE[10] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[11] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[12] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[13] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[14] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[15] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[16] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[17] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[18] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[19] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[20] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[21] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[22] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[23] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[24] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[25] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[26] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[27] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[28] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[29] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[30] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[31] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[32] = DATENOBJEKTE_KENNLINIE[0];
        SECOND_KENNLINIE[33] = DATENOBJEKTE_KENNLINIE[0];


    return SECOND_KENNLINIE;
    }

}
