package com.jess.gdfp;

public class DatenObjekteJob {

    public static int uiJobNr;
    public static byte ucJobTyp;
    public static int ucUserNr;
    public static int uiKennNr;
    public static byte ucKennTyp;
    public static int ucVerfahren;
    public static int ucBetriebsArt;
    public static int ucDrahtDurchm;
    public static int ucGasTyp;
    public static int ucWerkstoff;
    public static int ucReglerTyp;
    public static byte ucGasVor;
    public static byte ucGasNach;
    public static byte ucEinSchlAbs;
    public static byte scEinSchlProz;
    public static byte ucUpSlope;
    public static byte ucDownSlope;
    public static int ucZuendEgPrz;
    public static int ucEndKraterPrz;
    public static byte ucFreiBrandPrz;
    public static byte ucFreiBrandKorr;
    public static byte ucSynBasis;
    public static byte scKorrPulsAmpl;
    public static byte scKorrDrossel;
    public static int uiPausenZeit;
    public static int uiPunktZeit;
    public static byte ucEinfaedeln;
    public static byte ucZuendDauer;
    public static byte ucEndKraDauer;
    public static byte ucPPOnOff;
    public static byte ucPPEnergie2;
    public static byte ucPPTime1;
    public static byte ucPPTime2;
    public static byte scPP_LBR_E2;
    public static int uiZuendStrom;
    public static int uiZuendSpann;
    public static int uiZuendEnergie;
    public static byte ucZuendDrossel;
    public static byte scZuendLBKorr;
    public static int uiStufe1Strom;
    public static int uiStufe1Spann;
    public static int uiStufe1Energie;
    public static byte ucStufe1Drossel;
    public static byte scStufe1LBKorr;
    public static int uiStufe2Strom;
    public static int uiStufe2Spann;
    public static int uiStufe2Energie;
    public static byte ucStufe2Drossel;
    public static byte scStufe2LBKorr;
    public static int uiStufe3Strom;
    public static int uiStufe3Spann;
    public static int uiStufe3Energie;
    public static byte ucStufe3Drossel;
    public static byte scStufe3LBKorr;
    public static int uiEndKraStrom;
    public static int uiEndKraSpann;
    public static int uiEndKraEnergie;
    public static byte ucEndKraDrossel;
    public static byte scEndKraLBKorr;
    public static int uiVorschubSet;
    public static int uiStromSet;
    public static int uiSpannungSet;
    public static int uiBlechSet;
    public static int uiElektrStromSet;
    public static byte ucHotStartDauer;
    public static int ucHotStart;
    public static byte ucArcForce;
    public static byte ucElektrodeRI;
    public static int uiLimitEnergie;
    public static int uiLimitLbKorr;
    public static int uiStartAmplitude;
    public static byte ucStartZeit;
    public static int ucStartUeberh;
    public static byte ucDrosselRI;
    public static byte ucUeberBlendZeit;
    public static byte ucDrossAbfall;
    public static int ucMotorFlanke;
    public static byte ucDrossDynamic;
    public static byte ucLBR_Mode;
    public static byte ucBetriebMagAc;
    public static byte ucPosZeit;
    public static int uiNegZeit;
    public static byte ucKS_Erkenung;
    public static byte ucKS_Aufhebung;
    public static int ucVerwZeitPN;
    public static int ucVerwZeitNP;
    public static byte ucKaelteWert;
    public static byte ucStromSchwelle;
    public static int uiProtokollTyp;
    public static byte stJobBezZ1;
    public static byte stJobBezZ2;
    public static byte stJobBezZ3;
    public static int stJobKomm;
    public static int uiJobCRC;

    private static String[] JOB_PARAM = new String[120];

    public static String[] DataBase(){

        /*uiJobNr = (DatenObjekte.KENNLINIE_FRAME[8])+(DatenObjekte.KENNLINIE_FRAME[9]*256);
        ucJobTyp = (DatenObjekte.KENNLINIE_FRAME[10]);
        ucUserNr = (DatenObjekte.KENNLINIE_FRAME[11]);
        uiKennNr = (DatenObjekte.KENNLINIE_FRAME[12])+(DatenObjekte.KENNLINIE_FRAME[13]*256);
        ucKennTyp = (DatenObjekte.KENNLINIE_FRAME[14]);
        ucVerfahren = (DatenObjekte.KENNLINIE_FRAME[15]);
        ucBetriebsArt = (DatenObjekte.KENNLINIE_FRAME[16]);
        ucDrahtDurchm = (DatenObjekte.KENNLINIE_FRAME[17]);
        ucGasTyp = (DatenObjekte.KENNLINIE_FRAME[18]);
        ucWerkstoff = (DatenObjekte.KENNLINIE_FRAME[19]);
        ucReglerTyp = (DatenObjekte.KENNLINIE_FRAME[20]);
        ucGasVor = (DatenObjekte.KENNLINIE_FRAME[21]);
        ucGasNach = (DatenObjekte.KENNLINIE_FRAME[22]);
        ucEinSchlAbs = (DatenObjekte.KENNLINIE_FRAME[23]);
        scEinSchlProz = (DatenObjekte.KENNLINIE_FRAME[24]);
        ucUpSlope = (DatenObjekte.KENNLINIE_FRAME[25]);
        ucDownSlope = (DatenObjekte.KENNLINIE_FRAME[26]);
        ucZuendEgPrz = (DatenObjekte.KENNLINIE_FRAME[27]);
        ucEndKraterPrz = (DatenObjekte.KENNLINIE_FRAME[28]);
        ucFreiBrandPrz = (DatenObjekte.KENNLINIE_FRAME[29]);
        ucFreiBrandKorr = (DatenObjekte.KENNLINIE_FRAME[30]);
        ucSynBasis = (DatenObjekte.KENNLINIE_FRAME[31]);
        scKorrPulsAmpl = (DatenObjekte.KENNLINIE_FRAME[32]);
        scKorrDrossel = (DatenObjekte.KENNLINIE_FRAME[33]);
        uiPausenZeit = (DatenObjekte.KENNLINIE_FRAME[34])+(DatenObjekte.KENNLINIE_FRAME[35]*256);
        uiPunktZeit = (DatenObjekte.KENNLINIE_FRAME[36])+(DatenObjekte.KENNLINIE_FRAME[37]*256);
        ucEinfaedeln = (DatenObjekte.KENNLINIE_FRAME[38]);
        ucZuendDauer = (DatenObjekte.KENNLINIE_FRAME[39]);
        ucEndKraDauer = (DatenObjekte.KENNLINIE_FRAME[40]);
        ucPPOnOff = (DatenObjekte.KENNLINIE_FRAME[41]);
        ucPPEnergie2 = (DatenObjekte.KENNLINIE_FRAME[42]);
        ucPPTime1 = (DatenObjekte.KENNLINIE_FRAME[43]);
        ucPPTime2 = (DatenObjekte.KENNLINIE_FRAME[44]);
        scPP_LBR_E2 = (DatenObjekte.KENNLINIE_FRAME[45]);
        uiZuendStrom = (DatenObjekte.KENNLINIE_FRAME[46])+(DatenObjekte.KENNLINIE_FRAME[47]*256);
        uiZuendSpann = (DatenObjekte.KENNLINIE_FRAME[48])+(DatenObjekte.KENNLINIE_FRAME[49]*256);
        uiZuendEnergie = (DatenObjekte.KENNLINIE_FRAME[50])+(DatenObjekte.KENNLINIE_FRAME[51]*256);
        ucZuendDrossel = (DatenObjekte.KENNLINIE_FRAME[52]);
        scZuendLBKorr = (DatenObjekte.KENNLINIE_FRAME[53]);
        uiStufe1Strom = (DatenObjekte.KENNLINIE_FRAME[54])+(DatenObjekte.KENNLINIE_FRAME[55]*256);
        uiStufe1Spann = (DatenObjekte.KENNLINIE_FRAME[56])+(DatenObjekte.KENNLINIE_FRAME[57]*256);
        uiStufe1Energie = (DatenObjekte.KENNLINIE_FRAME[58])+(DatenObjekte.KENNLINIE_FRAME[59]*256);
        ucStufe1Drossel = (DatenObjekte.KENNLINIE_FRAME[60]);
        scStufe1LBKorr = (DatenObjekte.KENNLINIE_FRAME[61]);
        uiStufe2Strom = (DatenObjekte.KENNLINIE_FRAME[62])+(DatenObjekte.KENNLINIE_FRAME[63]*256);
        uiStufe2Spann = (DatenObjekte.KENNLINIE_FRAME[64])+(DatenObjekte.KENNLINIE_FRAME[65]*256);
        uiStufe2Energie = (DatenObjekte.KENNLINIE_FRAME[66])+(DatenObjekte.KENNLINIE_FRAME[67]*256);
        ucStufe2Drossel = (DatenObjekte.KENNLINIE_FRAME[68]);
        scStufe2LBKorr = (DatenObjekte.KENNLINIE_FRAME[69]);
        uiStufe3Strom = (DatenObjekte.KENNLINIE_FRAME[70])+(DatenObjekte.KENNLINIE_FRAME[71]*256);
        uiStufe3Spann = (DatenObjekte.KENNLINIE_FRAME[72])+(DatenObjekte.KENNLINIE_FRAME[73]*256);
        uiStufe3Energie = (DatenObjekte.KENNLINIE_FRAME[74])+(DatenObjekte.KENNLINIE_FRAME[75]*256);
        ucStufe3Drossel = (DatenObjekte.KENNLINIE_FRAME[76]);
        scStufe3LBKorr = (DatenObjekte.KENNLINIE_FRAME[77]);
        uiEndKraStrom = (DatenObjekte.KENNLINIE_FRAME[78])+(DatenObjekte.KENNLINIE_FRAME[79]*256);
        uiEndKraSpann = (DatenObjekte.KENNLINIE_FRAME[80])+(DatenObjekte.KENNLINIE_FRAME[81]*256);
        uiEndKraEnergie = (DatenObjekte.KENNLINIE_FRAME[82])+(DatenObjekte.KENNLINIE_FRAME[83]*256);
        ucEndKraDrossel = (DatenObjekte.KENNLINIE_FRAME[84]);
        scEndKraLBKorr = (DatenObjekte.KENNLINIE_FRAME[85]);
        uiVorschubSet = (DatenObjekte.KENNLINIE_FRAME[86 ])+(DatenObjekte.KENNLINIE_FRAME[87]*256);
        uiStromSet = (DatenObjekte.KENNLINIE_FRAME[88])+(DatenObjekte.KENNLINIE_FRAME[89]*256);
        uiSpannungSet = (DatenObjekte.KENNLINIE_FRAME[90])+(DatenObjekte.KENNLINIE_FRAME[91]*256);
        uiBlechSet = (DatenObjekte.KENNLINIE_FRAME[92])+(DatenObjekte.KENNLINIE_FRAME[93]*256);
        uiElektrStromSet = (DatenObjekte.KENNLINIE_FRAME[94])+(DatenObjekte.KENNLINIE_FRAME[95]*256);
        ucHotStartDauer = (DatenObjekte.KENNLINIE_FRAME[96]);
        ucHotStart = (DatenObjekte.KENNLINIE_FRAME[97]);
        ucArcForce = (DatenObjekte.KENNLINIE_FRAME[98]);
        ucElektrodeRI = (DatenObjekte.KENNLINIE_FRAME[99]);
        uiLimitEnergie = (DatenObjekte.KENNLINIE_FRAME[100])+(DatenObjekte.KENNLINIE_FRAME[101]*256);
        uiLimitLbKorr = (DatenObjekte.KENNLINIE_FRAME[102])+(DatenObjekte.KENNLINIE_FRAME[103]*256);
        uiStartAmplitude = (DatenObjekte.KENNLINIE_FRAME[104])+(DatenObjekte.KENNLINIE_FRAME[105]*256);
        ucStartZeit = (DatenObjekte.KENNLINIE_FRAME[106]);
        ucStartUeberh = (DatenObjekte.KENNLINIE_FRAME[107]);
        ucDrosselRI = (DatenObjekte.KENNLINIE_FRAME[108]);
        ucUeberBlendZeit = (DatenObjekte.KENNLINIE_FRAME[109]);
        ucDrossAbfall = (DatenObjekte.KENNLINIE_FRAME[110]);
        ucMotorFlanke = (DatenObjekte.KENNLINIE_FRAME[111]);
        ucDrossDynamic = (DatenObjekte.KENNLINIE_FRAME[112]);
        ucLBR_Mode = (DatenObjekte.KENNLINIE_FRAME[113]);
        ucBetriebMagAc = (DatenObjekte.KENNLINIE_FRAME[114]);
        ucPosZeit = (DatenObjekte.KENNLINIE_FRAME[115]);
        uiNegZeit = (DatenObjekte.KENNLINIE_FRAME[116])+(DatenObjekte.KENNLINIE_FRAME[117]*256);
        ucKS_Erkenung = (DatenObjekte.KENNLINIE_FRAME[118]);
        ucKS_Aufhebung = (DatenObjekte.KENNLINIE_FRAME[119]);
        ucVerwZeitPN = (DatenObjekte.KENNLINIE_FRAME[120]);
        ucVerwZeitNP = (DatenObjekte.KENNLINIE_FRAME[121]);
        ucKaelteWert = (DatenObjekte.KENNLINIE_FRAME[122]);
        ucStromSchwelle = (DatenObjekte.KENNLINIE_FRAME[123]);
        uiProtokollTyp = (DatenObjekte.KENNLINIE_FRAME[124])+(DatenObjekte.KENNLINIE_FRAME[125]*256);
        stJobBezZ1 = (DatenObjekte.KENNLINIE_FRAME[126]);
        stJobBezZ2 = (DatenObjekte.KENNLINIE_FRAME[142]);
        stJobBezZ3 = (DatenObjekte.KENNLINIE_FRAME[158]);
        stJobKomm = (DatenObjekte.KENNLINIE_FRAME[172]);
        uiJobCRC = (DatenObjekte.KENNLINIE_FRAME[302])+(DatenObjekte.KENNLINIE_FRAME[303]*256);*/

        uiJobNr = GlobalVariable.Jobnummer;
        ucJobTyp = (DatenObjekte.KENNLINIE_FRAME[10]);
        ucUserNr = GlobalVariable.UserNummer;
        uiKennNr =  GlobalVariable.Kennliniennummer;
        ucKennTyp = GlobalVariable.KennlinienTyp;
        ucVerfahren = GlobalVariable.SV1pos1;
        ucBetriebsArt = GlobalVariable.SV1pos2;
        ucDrahtDurchm = GlobalVariable.Drahtdurchmesser;
        ucGasTyp = GlobalVariable.SV1pos4;
        ucWerkstoff = GlobalVariable.SV1pos5;
        ucReglerTyp = GlobalVariable.SV1pos6;
        ucGasVor = GlobalVariable.Gasvorströmen;
        ucGasNach = GlobalVariable.Gasnachströmen;
        ucEinSchlAbs = GlobalVariable.EinschleichenAbsolut;
        scEinSchlProz = GlobalVariable.EinschleichenKorrektur;
        ucUpSlope = GlobalVariable.UpSlope;
        ucDownSlope = GlobalVariable.DownSlope;
        ucZuendEgPrz = GlobalVariable.Zündenergie;
        ucEndKraterPrz = GlobalVariable.Endkraterenergie;
        ucFreiBrandPrz = GlobalVariable.Freibrand;
        ucFreiBrandKorr = GlobalVariable.FreibandKorrektur;
        ucSynBasis = GlobalVariable.SynergieVorgabe;
        scKorrPulsAmpl = GlobalVariable.KorrekturPulsamplitude;
        scKorrDrossel = GlobalVariable.KorrekturDrossel;
        uiPausenZeit = GlobalVariable.PausenZeit;
        uiPunktZeit = GlobalVariable.Punktzeit;
        ucEinfaedeln = GlobalVariable.Einfädeln;
        ucZuendDauer = GlobalVariable.ZündDauer;
        ucEndKraDauer = GlobalVariable.EndkraterDauer;
        ucPPOnOff = GlobalVariable.PowerpulsEinAus;
        ucPPEnergie2 = GlobalVariable.PowerpulsE2;
        ucPPTime1 = GlobalVariable.PowerpulsT1E1;
        ucPPTime2 = GlobalVariable.PowerpulsT2E1;
        scPP_LBR_E2 = GlobalVariable.PowerpulsLBKorrE2;
        uiZuendStrom = GlobalVariable.ZündStrom;
        uiZuendSpann = GlobalVariable.ZündSpannung;
        uiZuendEnergie = GlobalVariable.ZündEnergie;
        ucZuendDrossel = GlobalVariable.ZündDrossel;
        scZuendLBKorr = GlobalVariable.ZündLichtbogenkorrektur;
        uiStufe1Strom = GlobalVariable.Strom1;
        uiStufe1Spann = GlobalVariable.Spannung1;
        uiStufe1Energie = GlobalVariable.Energie1;
        ucStufe1Drossel = GlobalVariable.Drossel1;
        scStufe1LBKorr = GlobalVariable.Lichtbogenkorrektur1;
        uiStufe2Strom = GlobalVariable.Strom2;
        uiStufe2Spann = GlobalVariable.Spannung2;
        uiStufe2Energie = GlobalVariable.Energie2;
        ucStufe2Drossel = GlobalVariable.Drossel2;
        scStufe2LBKorr = GlobalVariable.Lichtbogenkorrektur2;
        uiStufe3Strom = GlobalVariable.Strom3;
        uiStufe3Spann = GlobalVariable.Spannung3;
        uiStufe3Energie = GlobalVariable.Energie3;
        ucStufe3Drossel = GlobalVariable.Drossel3;
        scStufe3LBKorr = GlobalVariable.Lichtbogenkorrektur3;
        uiEndKraStrom = GlobalVariable.EndkraterStrom;
        uiEndKraSpann = GlobalVariable.EndkraterSpannung;
        uiEndKraEnergie = GlobalVariable.EndkraterEnergie;
        ucEndKraDrossel = GlobalVariable.EndkraterDrossel;
        scEndKraLBKorr = GlobalVariable.EndKraterLichtbogenkorrektur;
        uiVorschubSet =  GlobalVariable.VorschubSetwert;
        uiStromSet = GlobalVariable.StromSetwert;
        uiSpannungSet = GlobalVariable.SpannungSetwert;
        uiBlechSet = GlobalVariable.BlechdickeSetwert;
        uiElektrStromSet = GlobalVariable.ElektrodeStromSetwert;
        ucHotStartDauer = GlobalVariable.HotstartDauer;
        ucHotStart = GlobalVariable.Hotstart;
        ucArcForce = GlobalVariable.ArcForce;
        ucElektrodeRI = GlobalVariable.InnenwiderstandfürElektrode;
        uiLimitEnergie = (DatenObjekte.KENNLINIE_FRAME[100])+(DatenObjekte.KENNLINIE_FRAME[101]*256);
        uiLimitLbKorr = (DatenObjekte.KENNLINIE_FRAME[102])+(DatenObjekte.KENNLINIE_FRAME[103]*256);
        uiStartAmplitude =  GlobalVariable.StartAmplitude;
        ucStartZeit = GlobalVariable.StartZeit;
        ucStartUeberh = GlobalVariable.StartÜberhöhung;
        ucDrosselRI = GlobalVariable.InnenwiderstandfürDossel;
        ucUeberBlendZeit = GlobalVariable.Überblendzeit;
        ucDrossAbfall = GlobalVariable.DrosselAbfall;
        ucMotorFlanke = GlobalVariable.MotorFlanke;
        ucDrossDynamic = GlobalVariable.DrosselDynamic;
        ucLBR_Mode = GlobalVariable.LBRMode;
        ucBetriebMagAc = GlobalVariable.MAGACBetriebsart;
        ucPosZeit = GlobalVariable.MAGACPositiveZeit;
        uiNegZeit = GlobalVariable.MAGACNegativZeit;
        ucKS_Erkenung = GlobalVariable.MAGACKurzschlusserkennung;
        ucKS_Aufhebung = GlobalVariable.MAGACKurzschlussaufhebung;
        ucVerwZeitPN = GlobalVariable.MACAGVerweilzeitPosNeg;
        ucVerwZeitNP = GlobalVariable.MACAGVerweilzeitNegPos;
        ucKaelteWert = GlobalVariable.MAGACKältewert;
        ucStromSchwelle = GlobalVariable.WIGACStromoffset;
        uiProtokollTyp = (DatenObjekte.KENNLINIE_FRAME[124])+(DatenObjekte.KENNLINIE_FRAME[125]*256);
        stJobBezZ1 = (DatenObjekte.KENNLINIE_FRAME[126]);
        stJobBezZ2 = (DatenObjekte.KENNLINIE_FRAME[142]);
        stJobBezZ3 = (DatenObjekte.KENNLINIE_FRAME[158]);
        stJobKomm = GlobalVariable.JobKommando;
        uiJobCRC = (DatenObjekte.KENNLINIE_FRAME[302])+(DatenObjekte.KENNLINIE_FRAME[303]*256);

        JOB_PARAM[1] = String.valueOf(uiJobNr);
        JOB_PARAM[2] = String.valueOf(ucJobTyp);
        JOB_PARAM[3] = String.valueOf(ucUserNr);
        JOB_PARAM[4] = String.valueOf(uiKennNr);
        JOB_PARAM[5] = String.valueOf(ucKennTyp);
        JOB_PARAM[6] = String.valueOf(ucVerfahren);
        JOB_PARAM[7] = String.valueOf(ucBetriebsArt);
        JOB_PARAM[8] = String.valueOf(ucDrahtDurchm);
        JOB_PARAM[9] = String.valueOf(ucGasTyp);
        JOB_PARAM[10] = String.valueOf(ucWerkstoff);
        JOB_PARAM[11] = String.valueOf(ucReglerTyp);
        JOB_PARAM[12] = String.valueOf(ucGasVor);
        JOB_PARAM[13] = String.valueOf(ucGasNach);
        JOB_PARAM[14] = String.valueOf(ucEinSchlAbs);
        JOB_PARAM[15] = String.valueOf(scEinSchlProz);
        JOB_PARAM[16] = String.valueOf(ucUpSlope);
        JOB_PARAM[17] = String.valueOf(ucDownSlope);
        JOB_PARAM[19] = String.valueOf(ucZuendEgPrz);
        JOB_PARAM[20] = String.valueOf(ucEndKraterPrz);
        JOB_PARAM[21] = String.valueOf(ucFreiBrandPrz);
        JOB_PARAM[22] = String.valueOf(ucFreiBrandKorr);
        JOB_PARAM[23] = String.valueOf(ucSynBasis);
        JOB_PARAM[24] = String.valueOf(scKorrPulsAmpl);
        JOB_PARAM[25] = String.valueOf(scKorrDrossel);
        JOB_PARAM[26] = String.valueOf(uiPausenZeit);
        JOB_PARAM[27] = String.valueOf(uiPunktZeit);
        JOB_PARAM[28] = String.valueOf(ucEinfaedeln);
        JOB_PARAM[29] = String.valueOf(ucZuendDauer);
        JOB_PARAM[30] = String.valueOf(ucEndKraDauer);
        JOB_PARAM[31] = String.valueOf(ucPPOnOff);
        JOB_PARAM[32] = String.valueOf(ucPPEnergie2);
        JOB_PARAM[33] = String.valueOf(ucPPTime1);
        JOB_PARAM[34] = String.valueOf(ucPPTime2);
        JOB_PARAM[35] = String.valueOf(scPP_LBR_E2);
        JOB_PARAM[36] = String.valueOf(uiZuendStrom);
        JOB_PARAM[37] = String.valueOf(uiZuendSpann);
        JOB_PARAM[38] = String.valueOf(uiZuendEnergie);
        JOB_PARAM[39] = String.valueOf(ucZuendDrossel);
        JOB_PARAM[40] = String.valueOf(scZuendLBKorr);
        JOB_PARAM[41] = String.valueOf(uiStufe1Strom);
        JOB_PARAM[42] = String.valueOf(uiStufe1Spann);
        JOB_PARAM[43] = String.valueOf(uiStufe1Energie);
        JOB_PARAM[44] = String.valueOf(ucStufe1Drossel);
        JOB_PARAM[45] = String.valueOf(scStufe1LBKorr);
        JOB_PARAM[46] = String.valueOf(uiStufe2Strom);
        JOB_PARAM[47] = String.valueOf(uiStufe2Spann);
        JOB_PARAM[48] = String.valueOf(uiStufe2Energie);
        JOB_PARAM[49] = String.valueOf(ucStufe2Drossel);
        JOB_PARAM[50] = String.valueOf(scStufe2LBKorr);
        JOB_PARAM[51] = String.valueOf(uiStufe3Strom);
        JOB_PARAM[52] = String.valueOf(uiStufe3Spann);
        JOB_PARAM[53] = String.valueOf(uiStufe3Energie);
        JOB_PARAM[54] = String.valueOf(ucStufe3Drossel);
        JOB_PARAM[55] = String.valueOf(scStufe3LBKorr);
        JOB_PARAM[56] = String.valueOf(uiEndKraStrom);
        JOB_PARAM[57] = String.valueOf(uiEndKraSpann);
        JOB_PARAM[58] = String.valueOf(uiEndKraEnergie);
        JOB_PARAM[59] = String.valueOf(ucEndKraDrossel);
        JOB_PARAM[60] = String.valueOf(scEndKraLBKorr);
        JOB_PARAM[61] = String.valueOf(uiVorschubSet);
        JOB_PARAM[62] = String.valueOf(uiStromSet);
        JOB_PARAM[63] = String.valueOf(uiSpannungSet);
        JOB_PARAM[64] = String.valueOf(uiBlechSet);
        JOB_PARAM[65] = String.valueOf(uiElektrStromSet);
        JOB_PARAM[66] = String.valueOf(ucHotStartDauer);
        JOB_PARAM[67] = String.valueOf(ucHotStart);
        JOB_PARAM[68] = String.valueOf(ucArcForce);
        JOB_PARAM[69] = String.valueOf(ucElektrodeRI);
        JOB_PARAM[70] = String.valueOf(uiLimitEnergie);
        JOB_PARAM[71] = String.valueOf(uiLimitLbKorr);
        JOB_PARAM[72] = String.valueOf(uiStartAmplitude);
        JOB_PARAM[73] = String.valueOf(ucStartZeit);
        JOB_PARAM[74] = String.valueOf(ucStartUeberh);
        JOB_PARAM[75] = String.valueOf(ucDrosselRI);
        JOB_PARAM[76] = String.valueOf(ucUeberBlendZeit);
        JOB_PARAM[77] = String.valueOf(ucDrossAbfall);
        JOB_PARAM[78] = String.valueOf(ucMotorFlanke);
        JOB_PARAM[79] = String.valueOf(ucDrossDynamic);
        JOB_PARAM[80] = String.valueOf(ucLBR_Mode);
        JOB_PARAM[81] = String.valueOf(ucBetriebMagAc);
        JOB_PARAM[82] = String.valueOf(ucPosZeit);
        JOB_PARAM[83] = String.valueOf(uiNegZeit);
        JOB_PARAM[84] = String.valueOf(ucKS_Erkenung);
        JOB_PARAM[85] = String.valueOf(ucKS_Aufhebung);
        JOB_PARAM[86] = String.valueOf(ucVerwZeitPN);
        JOB_PARAM[87] = String.valueOf(ucVerwZeitNP);
        JOB_PARAM[88] = String.valueOf(ucKaelteWert);
        JOB_PARAM[89] = String.valueOf(ucStromSchwelle);
        JOB_PARAM[90] = String.valueOf(uiProtokollTyp);
        JOB_PARAM[91] = String.valueOf(stJobBezZ1);
        JOB_PARAM[92] = String.valueOf(stJobBezZ2);
        JOB_PARAM[93] = String.valueOf(stJobBezZ3);
        JOB_PARAM[94] = String.valueOf(stJobKomm);
        JOB_PARAM[95] = String.valueOf(uiJobCRC);

        return JOB_PARAM;
    }
}
