package com.jess.gdfp;

public class DatenObjekteJob {

    public static int uiJobNr;
    public static byte ucJobTyp;
    public static byte ucUserNr;
    public static int uiKennNr;
    public static byte ucKennTyp;
    public static byte ucVerfahren;
    public static byte ucBetriebsArt;
    public static byte ucDrahtDurchm;
    public static byte ucGasTyp;
    public static byte ucWerkstoff;
    public static byte ucReglerTyp;
    public static byte ucGasVor;
    public static byte ucGasNach;
    public static byte ucEinSchlAbs;
    public static byte scEinSchlProz;
    public static byte ucUpSlope;
    public static byte ucDownSlope;
    public static byte ucZuendEgPrz;
    public static byte ucEndKraterPrz;
    public static byte ucFreiBrandPrz;
    public static byte ucFreiBrandKorr;
    public static byte ucSynBasis;
    public static byte scKorrPulsAmpl;
    public static byte scKorrDrossel;
    public static int uiPausenZeit;
    public static int uiPunktZeit;
    public static byte ucEinfaedeln;
    public static byte ucZuendDauer;
    public static byte ucEndKraDauer;
    public static byte ucPPOnOff;
    public static byte ucPPEnergie2;
    public static byte ucPPTime1;
    public static byte ucPPTime2;
    public static byte scPP_LBR_E2;
    public static int uiZuendStrom;
    public static int uiZuendSpann;
    public static int uiZuendEnergie;
    public static byte ucZuendDrossel;
    public static byte scZuendLBKorr;
    public static int uiStufe1Strom;
    public static int uiStufe1Spann;
    public static int uiStufe1Energie;
    public static byte ucStufe1Drossel;
    public static byte scStufe1LBKorr;
    public static int uiStufe2Strom;
    public static int uiStufe2Spann;
    public static int uiStufe2Energie;
    public static byte ucStufe2Drossel;
    public static byte scStufe2LBKorr;
    public static int uiStufe3Strom;
    public static int uiStufe3Spann;
    public static int uiStufe3Energie;
    public static byte ucStufe3Drossel;
    public static byte scStufe3LBKorr;
    public static int uiEndKraStrom;
    public static int uiEndKraSpann;
    public static int uiEndKraEnergie;
    public static byte ucEndKraDrossel;
    public static byte scEndKraLBKorr;
    public static int uiVorschubSet;
    public static int uiStromSet;
    public static int uiSpannungSet;
    public static int uiBlechSet;
    public static int uiElektrStromSet;
    public static byte ucHotStartDauer;
    public static byte ucHotStart;
    public static byte ucArcForce;
    public static byte ucElektrodeRI;
    public static int uiLimitEnergie;
    public static int uiLimitLbKorr;
    public static int uiStartAmplitude;
    public static byte ucStartZeit;
    public static byte ucStartUeberh;
    public static byte ucDrosselRI;
    public static byte ucUeberBlendZeit;
    public static byte ucDrossAbfall;
    public static byte ucMotorFlanke;
    public static byte ucDrossDynamic;
    public static byte ucLBR_Mode;
    public static byte ucBetriebMagAc;
    public static byte ucPosZeit;
    public static int uiNegZeit;
    public static byte ucKS_Erkenung;
    public static byte ucKS_Aufhebung;
    public static byte ucVerwZeitPN;
    public static byte ucVerwZeitNP;
    public static byte ucKaelteWert;
    public static byte ucStromSchwelle;
    public static int uiProtokollTyp;
    public static byte stJobBezZ1;
    public static byte stJobBezZ2;
    public static byte stJobBezZ3;
    public static byte stJobKomm;
    public static int uiJobCRC;

    public static void DataBase(){

        uiJobNr = (DatenObjekte.KENNLINIE_FRAME[8])+(DatenObjekte.KENNLINIE_FRAME[9]*256);
        ucJobTyp = (DatenObjekte.KENNLINIE_FRAME[10]);
        ucUserNr = (DatenObjekte.KENNLINIE_FRAME[11]);
        uiKennNr = (DatenObjekte.KENNLINIE_FRAME[12])+(DatenObjekte.KENNLINIE_FRAME[13]*256);
        ucKennTyp = (DatenObjekte.KENNLINIE_FRAME[14]);
        ucVerfahren = (DatenObjekte.KENNLINIE_FRAME[15]);
        ucBetriebsArt = (DatenObjekte.KENNLINIE_FRAME[16]);
        ucDrahtDurchm = (DatenObjekte.KENNLINIE_FRAME[17]);
        ucGasTyp = (DatenObjekte.KENNLINIE_FRAME[18]);
        ucWerkstoff = (DatenObjekte.KENNLINIE_FRAME[19]);
        ucReglerTyp = (DatenObjekte.KENNLINIE_FRAME[20]);
        ucGasVor = (DatenObjekte.KENNLINIE_FRAME[21]);
        ucGasNach = (DatenObjekte.KENNLINIE_FRAME[22]);
        ucEinSchlAbs = (DatenObjekte.KENNLINIE_FRAME[23]);
        scEinSchlProz = (DatenObjekte.KENNLINIE_FRAME[24]);
        ucUpSlope = (DatenObjekte.KENNLINIE_FRAME[25]);
        ucDownSlope = (DatenObjekte.KENNLINIE_FRAME[26]);
        ucZuendEgPrz = (DatenObjekte.KENNLINIE_FRAME[27]);
        ucEndKraterPrz = (DatenObjekte.KENNLINIE_FRAME[28]);
        ucFreiBrandPrz = (DatenObjekte.KENNLINIE_FRAME[29]);
        ucFreiBrandKorr = (DatenObjekte.KENNLINIE_FRAME[30]);
        ucSynBasis = (DatenObjekte.KENNLINIE_FRAME[31]);
        scKorrPulsAmpl = (DatenObjekte.KENNLINIE_FRAME[32]);
        scKorrDrossel = (DatenObjekte.KENNLINIE_FRAME[33]);
        uiPausenZeit = (DatenObjekte.KENNLINIE_FRAME[34])+(DatenObjekte.KENNLINIE_FRAME[35]*256);
        uiPunktZeit = (DatenObjekte.KENNLINIE_FRAME[36])+(DatenObjekte.KENNLINIE_FRAME[37]*256);
        ucEinfaedeln = (DatenObjekte.KENNLINIE_FRAME[38]);
        ucZuendDauer = (DatenObjekte.KENNLINIE_FRAME[39]);
        ucEndKraDauer = (DatenObjekte.KENNLINIE_FRAME[40]);
        ucPPOnOff = (DatenObjekte.KENNLINIE_FRAME[41]);
        ucPPEnergie2 = (DatenObjekte.KENNLINIE_FRAME[42]);
        ucPPTime1 = (DatenObjekte.KENNLINIE_FRAME[43]);
        ucPPTime2 = (DatenObjekte.KENNLINIE_FRAME[44]);
        scPP_LBR_E2 = (DatenObjekte.KENNLINIE_FRAME[45]);
        uiZuendStrom = (DatenObjekte.KENNLINIE_FRAME[46])+(DatenObjekte.KENNLINIE_FRAME[47]*256);
        uiZuendSpann = (DatenObjekte.KENNLINIE_FRAME[48])+(DatenObjekte.KENNLINIE_FRAME[49]*256);
        uiZuendEnergie = (DatenObjekte.KENNLINIE_FRAME[50])+(DatenObjekte.KENNLINIE_FRAME[51]*256);
        ucZuendDrossel = (DatenObjekte.KENNLINIE_FRAME[52]);
        scZuendLBKorr = (DatenObjekte.KENNLINIE_FRAME[53]);
        uiStufe1Strom = (DatenObjekte.KENNLINIE_FRAME[54])+(DatenObjekte.KENNLINIE_FRAME[55]*256);
        uiStufe1Spann = (DatenObjekte.KENNLINIE_FRAME[56])+(DatenObjekte.KENNLINIE_FRAME[57]*256);
        uiStufe1Energie = (DatenObjekte.KENNLINIE_FRAME[58])+(DatenObjekte.KENNLINIE_FRAME[59]*256);
        ucStufe1Drossel = (DatenObjekte.KENNLINIE_FRAME[60]);
        scStufe1LBKorr = (DatenObjekte.KENNLINIE_FRAME[61]);
        uiStufe2Strom = (DatenObjekte.KENNLINIE_FRAME[62])+(DatenObjekte.KENNLINIE_FRAME[63]*256);
        uiStufe2Spann = (DatenObjekte.KENNLINIE_FRAME[64])+(DatenObjekte.KENNLINIE_FRAME[65]*256);
        uiStufe2Energie = (DatenObjekte.KENNLINIE_FRAME[66])+(DatenObjekte.KENNLINIE_FRAME[67]*256);
        ucStufe2Drossel = (DatenObjekte.KENNLINIE_FRAME[68]);
        scStufe2LBKorr = (DatenObjekte.KENNLINIE_FRAME[69]);
        uiStufe3Strom = (DatenObjekte.KENNLINIE_FRAME[70])+(DatenObjekte.KENNLINIE_FRAME[71]*256);
        uiStufe3Spann = (DatenObjekte.KENNLINIE_FRAME[72])+(DatenObjekte.KENNLINIE_FRAME[73]*256);
        uiStufe3Energie = (DatenObjekte.KENNLINIE_FRAME[74])+(DatenObjekte.KENNLINIE_FRAME[75]*256);
        ucStufe3Drossel = (DatenObjekte.KENNLINIE_FRAME[76]);
        scStufe3LBKorr = (DatenObjekte.KENNLINIE_FRAME[77]);
        uiEndKraStrom = (DatenObjekte.KENNLINIE_FRAME[78])+(DatenObjekte.KENNLINIE_FRAME[79]*256);
        uiEndKraSpann = (DatenObjekte.KENNLINIE_FRAME[80])+(DatenObjekte.KENNLINIE_FRAME[81]*256);
        uiEndKraEnergie = (DatenObjekte.KENNLINIE_FRAME[82])+(DatenObjekte.KENNLINIE_FRAME[83]*256);
        ucEndKraDrossel = (DatenObjekte.KENNLINIE_FRAME[84]);
        scEndKraLBKorr = (DatenObjekte.KENNLINIE_FRAME[85]);
        uiVorschubSet = (DatenObjekte.KENNLINIE_FRAME[86 ])+(DatenObjekte.KENNLINIE_FRAME[87]*256);
        uiStromSet = (DatenObjekte.KENNLINIE_FRAME[88])+(DatenObjekte.KENNLINIE_FRAME[89]*256);
        uiSpannungSet = (DatenObjekte.KENNLINIE_FRAME[90])+(DatenObjekte.KENNLINIE_FRAME[91]*256);
        uiBlechSet = (DatenObjekte.KENNLINIE_FRAME[92])+(DatenObjekte.KENNLINIE_FRAME[93]*256);
        uiElektrStromSet = (DatenObjekte.KENNLINIE_FRAME[94])+(DatenObjekte.KENNLINIE_FRAME[95]*256);
        ucHotStartDauer = (DatenObjekte.KENNLINIE_FRAME[96]);
        ucHotStart = (DatenObjekte.KENNLINIE_FRAME[97]);
        ucArcForce = (DatenObjekte.KENNLINIE_FRAME[98]);
        ucElektrodeRI = (DatenObjekte.KENNLINIE_FRAME[99]);
        uiLimitEnergie = (DatenObjekte.KENNLINIE_FRAME[100])+(DatenObjekte.KENNLINIE_FRAME[101]*256);
        uiLimitLbKorr = (DatenObjekte.KENNLINIE_FRAME[102])+(DatenObjekte.KENNLINIE_FRAME[103]*256);
        uiStartAmplitude = (DatenObjekte.KENNLINIE_FRAME[104])+(DatenObjekte.KENNLINIE_FRAME[105]*256);
        ucStartZeit = (DatenObjekte.KENNLINIE_FRAME[106]);
        ucStartUeberh = (DatenObjekte.KENNLINIE_FRAME[107]);
        ucDrosselRI = (DatenObjekte.KENNLINIE_FRAME[108]);
        ucUeberBlendZeit = (DatenObjekte.KENNLINIE_FRAME[109]);
        ucDrossAbfall = (DatenObjekte.KENNLINIE_FRAME[110]);
        ucMotorFlanke = (DatenObjekte.KENNLINIE_FRAME[111]);
        ucDrossDynamic = (DatenObjekte.KENNLINIE_FRAME[112]);
        ucLBR_Mode = (DatenObjekte.KENNLINIE_FRAME[113]);
        ucBetriebMagAc = (DatenObjekte.KENNLINIE_FRAME[114]);
        ucPosZeit = (DatenObjekte.KENNLINIE_FRAME[115]);
        uiNegZeit = (DatenObjekte.KENNLINIE_FRAME[116])+(DatenObjekte.KENNLINIE_FRAME[117]*256);
        ucKS_Erkenung = (DatenObjekte.KENNLINIE_FRAME[118]);
        ucKS_Aufhebung = (DatenObjekte.KENNLINIE_FRAME[119]);
        ucVerwZeitPN = (DatenObjekte.KENNLINIE_FRAME[120]);
        ucVerwZeitNP = (DatenObjekte.KENNLINIE_FRAME[121]);
        ucKaelteWert = (DatenObjekte.KENNLINIE_FRAME[122]);
        ucStromSchwelle = (DatenObjekte.KENNLINIE_FRAME[123]);
        uiProtokollTyp = (DatenObjekte.KENNLINIE_FRAME[124])+(DatenObjekte.KENNLINIE_FRAME[125]*256);
        stJobBezZ1 = (DatenObjekte.KENNLINIE_FRAME[126]);
        stJobBezZ2 = (DatenObjekte.KENNLINIE_FRAME[142]);
        stJobBezZ3 = (DatenObjekte.KENNLINIE_FRAME[158]);
        stJobKomm = (DatenObjekte.KENNLINIE_FRAME[172]);
        uiJobCRC = (DatenObjekte.KENNLINIE_FRAME[302])+(DatenObjekte.KENNLINIE_FRAME[303]*256);
    }
}
